version: '3'
services:
  spring-boot-postgres-docker-demo:
    image: spring-boot-postgres-docker-demo
    build: .
    command: mvn spring-boot:run -Dspring.profiles.active=docker
    volumes:
    - .:/spring-boot-code
    ports:
    - "9001:9001"
    links:
    - mypostgres
  mypostgres:
    image: postgres
    volumes:
    - data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=${DATABASE_USER}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    - POSTGRES_DB=${DATABASE_NAME}

volumes:
  data:
    external:
      name: postgres_docker_db